#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.3 on Sun Nov 25 22:09:39 2018
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((901, 753))
        self.combo_box_1 = wx.ComboBox(self, wx.ID_ANY, choices=["Square", "Sine", "Saw", "None"], style=wx.CB_DROPDOWN)
        self.combo_box_2 = wx.ComboBox(self, wx.ID_ANY, choices=["Square", "Sine", "Saw", "None"], style=wx.CB_DROPDOWN)
        self.combo_box_3 = wx.ComboBox(self, wx.ID_ANY, choices=["Square", "Sine", "Saw", "None"], style=wx.CB_DROPDOWN)
        self.radio_btn_1 = wx.RadioButton(self, wx.ID_ANY, "")
        self.radio_btn_2 = wx.RadioButton(self, wx.ID_ANY, "")
        self.radio_btn_3 = wx.RadioButton(self, wx.ID_ANY, "")
        self.combo_box_4 = wx.ComboBox(self, wx.ID_ANY, choices=["Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion", "None"], style=wx.CB_DROPDOWN)
        self.combo_box_5 = wx.ComboBox(self, wx.ID_ANY, choices=["Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion", "None"], style=wx.CB_DROPDOWN)
        self.combo_box_6 = wx.ComboBox(self, wx.ID_ANY, choices=["Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion", "None"], style=wx.CB_DROPDOWN)
        self.radio_btn_4 = wx.RadioButton(self, wx.ID_ANY, "")
        self.radio_btn_5 = wx.RadioButton(self, wx.ID_ANY, "")
        self.radio_btn_6 = wx.RadioButton(self, wx.ID_ANY, "")
        self.combo_box_7 = wx.ComboBox(self, wx.ID_ANY, choices=["Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion", "None"], style=wx.CB_DROPDOWN)
        self.combo_box_8 = wx.ComboBox(self, wx.ID_ANY, choices=["Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion", "None"], style=wx.CB_DROPDOWN)
        self.combo_box_9 = wx.ComboBox(self, wx.ID_ANY, choices=["Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion", "None"], style=wx.CB_DROPDOWN)
        self.radio_btn_7 = wx.RadioButton(self, wx.ID_ANY, "")
        self.radio_btn_8 = wx.RadioButton(self, wx.ID_ANY, "")
        self.radio_btn_9 = wx.RadioButton(self, wx.ID_ANY, "")
        self.combo_box_10 = wx.ComboBox(self, wx.ID_ANY, choices=["Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion", "None"], style=wx.CB_DROPDOWN)
        self.combo_box_11 = wx.ComboBox(self, wx.ID_ANY, choices=["Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion", "None"], style=wx.CB_DROPDOWN)
        self.combo_box_12 = wx.ComboBox(self, wx.ID_ANY, choices=["Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion", "None"], style=wx.CB_DROPDOWN)
        self.radio_btn_10 = wx.RadioButton(self, wx.ID_ANY, "")
        self.radio_btn_11 = wx.RadioButton(self, wx.ID_ANY, "")
        self.radio_btn_12 = wx.RadioButton(self, wx.ID_ANY, "")
        self.combo_box_13 = wx.ComboBox(self, wx.ID_ANY, choices=["Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion", "None"], style=wx.CB_DROPDOWN)
        self.combo_box_14 = wx.ComboBox(self, wx.ID_ANY, choices=["Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion", "None"], style=wx.CB_DROPDOWN)
        self.combo_box_15 = wx.ComboBox(self, wx.ID_ANY, choices=["Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion", "None"], style=wx.CB_DROPDOWN)
        self.radio_btn_13 = wx.RadioButton(self, wx.ID_ANY, "")
        self.radio_btn_14 = wx.RadioButton(self, wx.ID_ANY, "")
        self.radio_btn_15 = wx.RadioButton(self, wx.ID_ANY, "")
        self.combo_box_16 = wx.ComboBox(self, wx.ID_ANY, choices=["Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion", "None"], style=wx.CB_DROPDOWN)
        self.combo_box_17 = wx.ComboBox(self, wx.ID_ANY, choices=["Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion", "None"], style=wx.CB_DROPDOWN)
        self.combo_box_18 = wx.ComboBox(self, wx.ID_ANY, choices=["Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion", "None"], style=wx.CB_DROPDOWN)
        self.radio_btn_16 = wx.RadioButton(self, wx.ID_ANY, "")
        self.radio_btn_17 = wx.RadioButton(self, wx.ID_ANY, "")
        self.radio_btn_18 = wx.RadioButton(self, wx.ID_ANY, "")
        
        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Set Input Device", "")
        self.Bind(wx.EVT_MENU, self.setInputMidi, id=item.GetId())
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Set Output Device", "")
        self.Bind(wx.EVT_MENU, self.setOutputMidi, id=item.GetId())
        self.frame_menubar.Append(wxglade_tmp_menu, "Set I/O Device")
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Save Current Preset", "")
        self.Bind(wx.EVT_MENU, self.savePreset, id=item.GetId())
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Load Preset", "")
        self.Bind(wx.EVT_MENU, self.loadPreset, id=item.GetId())
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Build New Preset", "")
        self.Bind(wx.EVT_MENU, self.newPreset, id=item.GetId())
        self.frame_menubar.Append(wxglade_tmp_menu, "Save/Load/New Preset")
        wxglade_tmp_menu = wx.Menu()
        self.frame_menubar.Append(wxglade_tmp_menu, "Reboot Audio Server")
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end

        self.__set_properties()
        self.__do_layout()

        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Synth App")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_2 = wx.GridSizer(0, 3, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        Label1 = wx.StaticText(self, wx.ID_ANY, "Voice 1")
        Label1.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        grid_sizer_2.Add(Label1, 0, wx.ALIGN_CENTER, 0)
        Label1_copy = wx.StaticText(self, wx.ID_ANY, "Voice 2")
        Label1_copy.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        grid_sizer_2.Add(Label1_copy, 0, wx.ALIGN_CENTER, 0)
        Label1_copy_1 = wx.StaticText(self, wx.ID_ANY, "Voice 3")
        Label1_copy_1.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        grid_sizer_2.Add(Label1_copy_1, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        label_1 = wx.StaticText(self, wx.ID_ANY, "Waveform Selection")
        label_1.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 1, ""))
        grid_sizer_2.Add(label_1, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add(self.combo_box_1, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_2, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_3, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.radio_btn_1, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.radio_btn_2, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.radio_btn_3, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        label_2 = wx.StaticText(self, wx.ID_ANY, "Filters")
        label_2.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 1, ""))
        grid_sizer_2.Add(label_2, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add(self.combo_box_4, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_5, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_6, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.radio_btn_4, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.radio_btn_5, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.radio_btn_6, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.combo_box_7, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_8, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_9, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.radio_btn_7, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.radio_btn_8, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.radio_btn_9, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.combo_box_10, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_11, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_12, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.radio_btn_10, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.radio_btn_11, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.radio_btn_12, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.combo_box_13, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_14, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_15, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.radio_btn_13, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.radio_btn_14, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.radio_btn_15, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.combo_box_16, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_17, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_18, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.radio_btn_16, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.radio_btn_17, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.radio_btn_18, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def setInputMidi(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'setInputMidi' not implemented!")
        event.Skip()

    def setOutputMidi(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'setOutputMidi' not implemented!")
        event.Skip()

    def savePreset(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'savePreset' not implemented!")
        event.Skip()

    def loadPreset(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'loadPreset' not implemented!")
        event.Skip()

    def newPreset(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'newPreset' not implemented!")
        event.Skip()

    def rebootAudioServer(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'rebootAudioServer' not implemented!")
        event.Skip()

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
