#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.3 on Sun Nov 25 22:09:39 2018
#

import wx
from Util.EnumData import Bools, Nums
from Controllers.Router import Router

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((901, 753))

        #Start the synth.
        Router(Nums.START.value, Nums.PASS.value)

        #Sets up Voice1 options.
        self.combo_box_1 = wx.ComboBox(self, wx.ID_ANY, choices=["None", "Sine", "Square", "Saw"], style=wx.CB_READONLY)
        self.combo_box_1.Bind(wx.EVT_COMBOBOX, self.editVoice1, self.combo_box_1)
        self.muteBtn1 = wx.CheckBox(self, wx.ID_ANY, "")
        self.muteBtn1.Bind(wx.EVT_CHECKBOX, self.muteVoice1)

        #Sets up Voice2 options.
        self.combo_box_2 = wx.ComboBox(self, wx.ID_ANY, choices=["None", "Sine", "Square", "Saw"], style=wx.CB_READONLY)
        self.combo_box_2.Bind(wx.EVT_COMBOBOX, self.editVoice2, self.combo_box_2)
        self.muteBtn2 = wx.CheckBox(self, wx.ID_ANY, "")
        self.muteBtn2.Bind(wx.EVT_CHECKBOX, self.muteVoice2)

        #Sets up Voice3 options.
        self.combo_box_3 = wx.ComboBox(self, wx.ID_ANY, choices=["None", "Sine", "Square", "Saw"], style=wx.CB_READONLY)
        self.combo_box_3.Bind(wx.EVT_COMBOBOX, self.editVoice3, self.combo_box_3)
        self.muteBtn3 = wx.CheckBox(self, wx.ID_ANY, "")
        self.muteBtn3.Bind(wx.EVT_CHECKBOX, self.muteVoice3)

        #V1F1
        self.combo_box_4 = wx.ComboBox(self, wx.ID_ANY, choices=["None", "Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion"], style=wx.CB_READONLY)
        self.combo_box_4.Bind(wx.EVT_COMBOBOX, self.editV1F1, self.combo_box_4)
        self.muteBtn4 = wx.CheckBox(self, wx.ID_ANY, "")
        self.muteBtn4.Bind(wx.EVT_CHECKBOX, self.muteV1F1)

        #V2F1
        self.combo_box_5 = wx.ComboBox(self, wx.ID_ANY, choices=["None", "Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion"], style=wx.CB_READONLY)
        self.combo_box_5.Bind(wx.EVT_COMBOBOX, self.editV2F1, self.combo_box_5)
        self.muteBtn5 = wx.CheckBox(self, wx.ID_ANY, "")
        self.muteBtn5.Bind(wx.EVT_CHECKBOX, self.muteV2F1)

        #V3F1
        self.combo_box_6 = wx.ComboBox(self, wx.ID_ANY, choices=["None", "Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion"], style=wx.CB_READONLY)
        self.combo_box_6.Bind(wx.EVT_COMBOBOX, self.editV3F1, self.combo_box_6)
        self.muteBtn6 = wx.CheckBox(self, wx.ID_ANY, "")
        self.muteBtn6.Bind(wx.EVT_CHECKBOX, self.muteV3F1)

        #V1F2
        self.combo_box_7 = wx.ComboBox(self, wx.ID_ANY, choices=["None", "Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion"], style=wx.CB_READONLY)
        self.combo_box_7.Bind(wx.EVT_COMBOBOX, self.editV1F2, self.combo_box_7)
        self.muteBtn7 = wx.CheckBox(self, wx.ID_ANY, "")
        self.muteBtn7.Bind(wx.EVT_CHECKBOX, self.muteV1F2)

        #V2F2
        self.combo_box_8 = wx.ComboBox(self, wx.ID_ANY, choices=["None", "Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion"], style=wx.CB_READONLY)
        self.combo_box_8.Bind(wx.EVT_COMBOBOX, self.editV2F2, self.combo_box_8)
        self.muteBtn8 = wx.CheckBox(self, wx.ID_ANY, "")
        self.muteBtn8.Bind(wx.EVT_CHECKBOX, self.muteV2F2)

        #V3F2
        self.combo_box_9 = wx.ComboBox(self, wx.ID_ANY, choices=["None", "Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion"], style=wx.CB_READONLY)
        self.combo_box_9.Bind(wx.EVT_COMBOBOX, self.editV3F2, self.combo_box_9)
        self.muteBtn9 = wx.CheckBox(self, wx.ID_ANY, "")
        self.muteBtn9.Bind(wx.EVT_CHECKBOX, self.muteV3F2)

        #V1F3
        self.combo_box_10 = wx.ComboBox(self, wx.ID_ANY, choices=["None", "Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion"], style=wx.CB_READONLY)
        self.combo_box_10.Bind(wx.EVT_COMBOBOX, self.editV1F3, self.combo_box_10)
        self.muteBtn10 = wx.CheckBox(self, wx.ID_ANY, "")
        self.muteBtn10.Bind(wx.EVT_CHECKBOX, self.muteV1F3)

        #V2F3
        self.combo_box_11 = wx.ComboBox(self, wx.ID_ANY, choices=["None", "Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion"], style=wx.CB_READONLY)
        self.combo_box_11.Bind(wx.EVT_COMBOBOX, self.editV2F3, self.combo_box_11)
        self.muteBtn11 = wx.CheckBox(self, wx.ID_ANY, "")
        self.muteBtn11.Bind(wx.EVT_CHECKBOX, self.muteV2F3)

        #V3F3
        self.combo_box_12 = wx.ComboBox(self, wx.ID_ANY, choices=["None", "Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion"], style=wx.CB_READONLY)
        self.combo_box_12.Bind(wx.EVT_COMBOBOX, self.editV3F3, self.combo_box_12)
        self.muteBtn12 = wx.CheckBox(self, wx.ID_ANY, "")
        self.muteBtn12.Bind(wx.EVT_CHECKBOX, self.muteV3F3)

        #V1F4
        self.combo_box_13 = wx.ComboBox(self, wx.ID_ANY, choices=["None", "Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion"], style=wx.CB_READONLY)
        self.combo_box_13.Bind(wx.EVT_COMBOBOX, self.editV1F4, self.combo_box_13)
        self.muteBtn13 = wx.CheckBox(self, wx.ID_ANY, "")
        self.muteBtn13.Bind(wx.EVT_CHECKBOX, self.muteV1F4)


        #V2F4
        self.combo_box_14 = wx.ComboBox(self, wx.ID_ANY, choices=["None", "Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion"], style=wx.CB_READONLY)
        self.combo_box_14.Bind(wx.EVT_COMBOBOX, self.editV2F4, self.combo_box_14)
        self.muteBtn14 = wx.CheckBox(self, wx.ID_ANY, "")
        self.muteBtn14.Bind(wx.EVT_CHECKBOX, self.muteV2F4)

        #V3F4
        self.combo_box_15 = wx.ComboBox(self, wx.ID_ANY, choices=["None", "Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion"], style=wx.CB_READONLY)
        self.combo_box_15.Bind(wx.EVT_COMBOBOX, self.editV3F4, self.combo_box_15)
        self.muteBtn15 = wx.CheckBox(self, wx.ID_ANY, "")
        self.muteBtn15.Bind(wx.EVT_CHECKBOX, self.muteV3F4)

        #V1F5
        self.combo_box_16 = wx.ComboBox(self, wx.ID_ANY, choices=["None", "Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion"], style=wx.CB_READONLY)
        self.combo_box_16.Bind(wx.EVT_COMBOBOX, self.editV1F5, self.combo_box_16)
        self.muteBtn16 = wx.CheckBox(self, wx.ID_ANY, "")
        self.muteBtn16.Bind(wx.EVT_CHECKBOX, self.muteV1F5)

        #V2F5
        self.combo_box_17 = wx.ComboBox(self, wx.ID_ANY, choices=["None", "Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion"], style=wx.CB_READONLY)
        self.combo_box_17.Bind(wx.EVT_COMBOBOX, self.editV2F5, self.combo_box_17)
        self.muteBtn17 = wx.CheckBox(self, wx.ID_ANY, "")
        self.muteBtn17.Bind(wx.EVT_CHECKBOX, self.muteV2F5)

        #V3F5
        self.combo_box_18 = wx.ComboBox(self, wx.ID_ANY, choices=["None", "Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion"], style=wx.CB_READONLY)
        self.combo_box_18.Bind(wx.EVT_COMBOBOX, self.editV3F5, self.combo_box_18)
        self.muteBtn18 = wx.CheckBox(self, wx.ID_ANY, "")
        self.muteBtn18.Bind(wx.EVT_CHECKBOX, self.muteV3F5)

        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Set Input Device", "")
        self.Bind(wx.EVT_MENU, self.setInputMidi, id=item.GetId())
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Set Output Device", "")
        self.Bind(wx.EVT_MENU, self.setOutputMidi, id=item.GetId())
        self.frame_menubar.Append(wxglade_tmp_menu, "Set I/O Device")
        wxglade_tmp_menu = wx.Menu()

        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Save Current Preset", "")
        self.Bind(wx.EVT_MENU, self.savePreset, id=item.GetId())
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Load Preset", "")
        self.Bind(wx.EVT_MENU, self.loadPreset, id=item.GetId())
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Build New Preset", "")
        self.Bind(wx.EVT_MENU, self.newPreset, id=item.GetId())
        self.frame_menubar.Append(wxglade_tmp_menu, "Save/Load/New Preset")
        wxglade_tmp_menu = wx.Menu()

        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Boot", "")
        self.Bind(wx.EVT_MENU, self.bootAudioServer, id=item.GetId())
        self.frame_menubar.Append(wxglade_tmp_menu, "Boot Audio Server")
        wxglade_tmp_menu = wx.Menu()

        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end

        self.__set_properties()
        self.__do_layout()

        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Synth App")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_2 = wx.GridSizer(0, 3, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)

        Label1 = wx.StaticText(self, wx.ID_ANY, "Voice 1")
        Label1.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        grid_sizer_2.Add(Label1, 0, wx.ALIGN_CENTER, 0)
        Label1_copy = wx.StaticText(self, wx.ID_ANY, "Voice 2")
        Label1_copy.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        grid_sizer_2.Add(Label1_copy, 0, wx.ALIGN_CENTER, 0)
        Label1_copy_1 = wx.StaticText(self, wx.ID_ANY, "Voice 3")
        Label1_copy_1.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        grid_sizer_2.Add(Label1_copy_1, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)

        label_1 = wx.StaticText(self, wx.ID_ANY, "Waveform Selection")
        label_1.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 1, ""))
        grid_sizer_2.Add(label_1, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add(self.combo_box_1, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_2, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_3, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.muteBtn1, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.muteBtn2, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.muteBtn3, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)

        label_2 = wx.StaticText(self, wx.ID_ANY, "Filters")
        label_2.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 1, ""))
        grid_sizer_2.Add(label_2, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add(self.combo_box_4, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_5, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_6, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.muteBtn4, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.muteBtn5, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.muteBtn6, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.combo_box_7, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_8, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_9, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.muteBtn7, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.muteBtn8, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.muteBtn9, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.combo_box_10, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_11, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_12, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.muteBtn10, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.muteBtn11, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.muteBtn12, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.combo_box_13, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_14, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_15, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.muteBtn13, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.muteBtn14, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.muteBtn15, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.combo_box_16, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_17, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.combo_box_18, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.muteBtn16, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.muteBtn17, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.muteBtn18, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)
        grid_sizer_2.Add((0, 0), 0, 0, 0)

        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    #Menu bar events
    def setInputMidi(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'setInputMidi' not implemented!")
        event.Skip()

    def setOutputMidi(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'setOutputMidi' not implemented!")
        event.Skip()

    def savePreset(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'savePreset' not implemented!")
        event.Skip()

    def loadPreset(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'loadPreset' not implemented!")
        event.Skip()

    def newPreset(self, event):  # wxGlade: MyFrame.<event_handler>
        self.combo_box_1.SetSelection(0)
        self.combo_box_2.SetSelection(0)
        self.combo_box_3.SetSelection(0)
        self.combo_box_4.SetSelection(0)
        self.combo_box_5.SetSelection(0)
        self.combo_box_6.SetSelection(0)
        self.combo_box_7.SetSelection(0)
        self.combo_box_8.SetSelection(0)
        self.combo_box_9.SetSelection(0)
        self.combo_box_10.SetSelection(0)
        self.combo_box_11.SetSelection(0)
        self.combo_box_12.SetSelection(0)
        self.combo_box_13.SetSelection(0)
        self.combo_box_14.SetSelection(0)
        self.combo_box_15.SetSelection(0)
        self.combo_box_16.SetSelection(0)
        self.combo_box_17.SetSelection(0)
        self.combo_box_18.SetSelection(0)
        self.muteBtn1.SetValue(False)
        self.muteBtn2.SetValue(False)
        self.muteBtn3.SetValue(False)
        self.muteBtn4.SetValue(False)
        self.muteBtn5.SetValue(False)
        self.muteBtn6.SetValue(False)
        self.muteBtn7.SetValue(False)
        self.muteBtn8.SetValue(False)
        self.muteBtn9.SetValue(False)
        self.muteBtn10.SetValue(False)
        self.muteBtn11.SetValue(False)
        self.muteBtn12.SetValue(False)
        self.muteBtn13.SetValue(False)
        self.muteBtn14.SetValue(False)
        self.muteBtn15.SetValue(False)
        self.muteBtn16.SetValue(False)
        self.muteBtn17.SetValue(False)
        self.muteBtn18.SetValue(False)
        Router(Nums.REFRESH.value, Nums.PASS.value)

    def bootAudioServer(self, event):  # wxGlade: MyFrame.<event_handler>
        Router(Nums.BOOT.value, Nums.PASS.value)

    #VOICE1 and FILTERS
    #"Chorus", "Harmonizer", "Frequency Shift", "Reverb", "Distortion", "None"
    def editVoice1(self, event):
        if (self.combo_box_1.GetValue() == "Square"):
            Router(Nums.VOICE1.value, Nums.OSC.value)
        elif (self.combo_box_1.GetValue() == "Sine"):
            Router(Nums.VOICE1.value, Nums.SIN.value)
        elif (self.combo_box_1.GetValue() == "Saw"):
            Router(Nums.VOICE1.value, Nums.SAW.value)
        elif (self.combo_box_1.GetValue() == "None"):
            Router(Nums.VOICE1.value, Nums.NONE.value)

    def muteVoice1(self, event):
        Router(Nums.VOICE1.value, Nums.TOGGLE.value)

    def editV1F1(self, event):
        if (self.combo_box_4.GetValue() == "Chorus"):
            Router(Nums.V1F1.value, Nums.CHOR.value)
        elif (self.combo_box_4.GetValue() == "Harmonizer"):
            Router(Nums.V1F1.value, Nums.HARM.value)
        elif (self.combo_box_4.GetValue() == "Frequency Shift"):
            Router(Nums.V1F1.value, Nums.FREQ.value)
        elif (self.combo_box_4.GetValue() == "Reverb"):
            Router(Nums.V1F1.value, Nums.RVRB.value)
        elif (self.combo_box_4.GetValue() == "Distortion"):
            Router(Nums.V1F1.value, Nums.DIST.value)
        elif (self.combo_box_4.GetValue() == "None"):
            Router(Nums.V1F1.value, Nums.NONE.value)

    def muteV1F1(self, event):
        Router(Nums.V1F1.value, Nums.TOGGLE.value)

    def editV1F2(self, event):
        if (self.combo_box_7.GetValue() == "Chorus"):
            Router(Nums.V1F2.value, Nums.CHOR.value)
        elif (self.combo_box_7.GetValue() == "Harmonizer"):
            Router(Nums.V1F2.value, Nums.HARM.value)
        elif (self.combo_box_7.GetValue() == "Frequency Shift"):
            Router(Nums.V1F2.value, Nums.FREQ.value)
        elif (self.combo_box_7.GetValue() == "Reverb"):
            Router(Nums.V1F2.value, Nums.RVRB.value)
        elif (self.combo_box_7.GetValue() == "Distortion"):
            Router(Nums.V1F2.value, Nums.DIST.value)
        elif (self.combo_box_7.GetValue() == "None"):
            Router(Nums.V1F2.value, Nums.NONE.value)

    def muteV1F2(self, event):
        Router(Nums.V1F2.value, Nums.TOGGLE.value)

    def editV1F3(self, event):
        if (self.combo_box_10.GetValue() == "Chorus"):
            Router(Nums.V1F3.value, Nums.CHOR.value)
        elif (self.combo_box_10.GetValue() == "Harmonizer"):
            Router(Nums.V1F3.value, Nums.HARM.value)
        elif (self.combo_box_10.GetValue() == "Frequency Shift"):
            Router(Nums.V1F3.value, Nums.FREQ.value)
        elif (self.combo_box_10.GetValue() == "Reverb"):
            Router(Nums.V1F3.value, Nums.RVRB.value)
        elif (self.combo_box_10.GetValue() == "Distortion"):
            Router(Nums.V1F3.value, Nums.DIST.value)
        elif (self.combo_box_10.GetValue() == "None"):
            Router(Nums.V1F3.value, Nums.NONE.value)

    def muteV1F3(self, event):
        Router(Nums.V1F3.value, Nums.TOGGLE.value)

    def editV1F4(self, event):
        if (self.combo_box_13.GetValue() == "Chorus"):
            Router(Nums.V1F4.value, Nums.CHOR.value)
        elif (self.combo_box_13.GetValue() == "Harmonizer"):
            Router(Nums.V1F4.value, Nums.HARM.value)
        elif (self.combo_box_13.GetValue() == "Frequency Shift"):
            Router(Nums.V1F4.value, Nums.FREQ.value)
        elif (self.combo_box_13.GetValue() == "Reverb"):
            Router(Nums.V1F4.value, Nums.RVRB.value)
        elif (self.combo_box_13.GetValue() == "Distortion"):
            Router(Nums.V1F4.value, Nums.DIST.value)
        elif (self.combo_box_13.GetValue() == "None"):
            Router(Nums.V1F4.value, Nums.NONE.value)

    def muteV1F4(self, event):
        Router(Nums.V1F4.value, Nums.TOGGLE.value)

    def editV1F5(self, event):
        if (self.combo_box_16.GetValue() == "Chorus"):
            Router(Nums.V1F5.value, Nums.CHOR.value)
        elif (self.combo_box_16.GetValue() == "Harmonizer"):
            Router(Nums.V1F5.value, Nums.HARM.value)
        elif (self.combo_box_16.GetValue() == "Frequency Shift"):
            Router(Nums.V1F5.value, Nums.FREQ.value)
        elif (self.combo_box_16.GetValue() == "Reverb"):
            Router(Nums.V1F5.value, Nums.RVRB.value)
        elif (self.combo_box_16.GetValue() == "Distortion"):
            Router(Nums.V1F5.value, Nums.DIST.value)
        elif (self.combo_box_16.GetValue() == "None"):
            Router(Nums.V1F5.value, Nums.NONE.value)

    def muteV1F5(self, event):
        Router(Nums.V1F5.value, Nums.TOGGLE.value)

    #VOICE2 and FILTERS
    def editVoice2(self, event):
        if (self.combo_box_2.GetValue() == "Square"):
            Router(Nums.VOICE2.value, Nums.OSC.value)
        elif (self.combo_box_2.GetValue() == "Sine"):
            Router(Nums.VOICE2.value, Nums.SIN.value)
        elif (self.combo_box_2.GetValue() == "Saw"):
            Router(Nums.VOICE2.value, Nums.SAW.value)
        elif (self.combo_box_2.GetValue() == "None"):
            Router(Nums.VOICE2.value, Nums.NONE.value)

    def muteVoice2(self, event):
        Router(Nums.VOICE2.value, Nums.TOGGLE.value)

    def editV2F1(self, event):
        if (self.combo_box_5.GetValue() == "Chorus"):
            Router(Nums.V2F1.value, Nums.CHOR.value)
        elif (self.combo_box_5.GetValue() == "Harmonizer"):
            Router(Nums.V2F1.value, Nums.HARM.value)
        elif (self.combo_box_5.GetValue() == "Frequency Shift"):
            Router(Nums.V2F1.value, Nums.FREQ.value)
        elif (self.combo_box_5.GetValue() == "Reverb"):
            Router(Nums.V2F1.value, Nums.RVRB.value)
        elif (self.combo_box_5.GetValue() == "Distortion"):
            Router(Nums.V2F1.value, Nums.DIST.value)
        elif (self.combo_box_5.GetValue() == "None"):
            Router(Nums.V2F1.value, Nums.NONE.value)

    def muteV2F1(self, event):
        Router(Nums.V2F1.value, Nums.TOGGLE.value)

    def editV2F2(self, event):
        if (self.combo_box_8.GetValue() == "Chorus"):
            Router(Nums.V2F2.value, Nums.CHOR.value)
        elif (self.combo_box_8.GetValue() == "Harmonizer"):
            Router(Nums.V2F2.value, Nums.HARM.value)
        elif (self.combo_box_8.GetValue() == "Frequency Shift"):
            Router(Nums.V2F2.value, Nums.FREQ.value)
        elif (self.combo_box_8.GetValue() == "Reverb"):
            Router(Nums.V2F2.value, Nums.RVRB.value)
        elif (self.combo_box_8.GetValue() == "Distortion"):
            Router(Nums.V2F2.value, Nums.DIST.value)
        elif (self.combo_box_8.GetValue() == "None"):
            Router(Nums.V2F2.value, Nums.NONE.value)

    def muteV2F2(self, event):
        Router(Nums.V2F2.value, Nums.TOGGLE.value)

    def editV2F3(self, event):
        if (self.combo_box_11.GetValue() == "Chorus"):
            Router(Nums.V2F3.value, Nums.CHOR.value)
        elif (self.combo_box_11.GetValue() == "Harmonizer"):
            Router(Nums.V2F3.value, Nums.HARM.value)
        elif (self.combo_box_11.GetValue() == "Frequency Shift"):
            Router(Nums.V2F3.value, Nums.FREQ.value)
        elif (self.combo_box_11.GetValue() == "Reverb"):
            Router(Nums.V2F3.value, Nums.RVRB.value)
        elif (self.combo_box_11.GetValue() == "Distortion"):
            Router(Nums.V2F3.value, Nums.DIST.value)
        elif (self.combo_box_11.GetValue() == "None"):
            Router(Nums.V2F3.value, Nums.NONE.value)

    def muteV2F3(self, event):
        Router(Nums.V2F3.value, Nums.TOGGLE.value)

    def editV2F4(self, event):
        if (self.combo_box_14.GetValue() == "Chorus"):
            Router(Nums.V2F4.value, Nums.CHOR.value)
        elif (self.combo_box_14.GetValue() == "Harmonizer"):
            Router(Nums.V2F4.value, Nums.HARM.value)
        elif (self.combo_box_14.GetValue() == "Frequency Shift"):
            Router(Nums.V2F4.value, Nums.FREQ.value)
        elif (self.combo_box_14.GetValue() == "Reverb"):
            Router(Nums.V2F4.value, Nums.RVRB.value)
        elif (self.combo_box_14.GetValue() == "Distortion"):
            Router(Nums.V2F4.value, Nums.DIST.value)
        elif (self.combo_box_14.GetValue() == "None"):
            Router(Nums.V2F4.value, Nums.NONE.value)

    def muteV2F4(self, event):
        Router(Nums.V2F4.value, Nums.TOGGLE.value)

    def editV2F5(self, event):
        if (self.combo_box_17.GetValue() == "Chorus"):
            Router(Nums.V2F5.value, Nums.CHOR.value)
        elif (self.combo_box_17.GetValue() == "Harmonizer"):
            Router(Nums.V2F5.value, Nums.HARM.value)
        elif (self.combo_box_17.GetValue() == "Frequency Shift"):
            Router(Nums.V2F5.value, Nums.FREQ.value)
        elif (self.combo_box_17.GetValue() == "Reverb"):
            Router(Nums.V2F5.value, Nums.RVRB.value)
        elif (self.combo_box_17.GetValue() == "Distortion"):
            Router(Nums.V2F5.value, Nums.DIST.value)
        elif (self.combo_box_17.GetValue() == "None"):
            Router(Nums.V2F5.value, Nums.NONE.value)

    def muteV2F5(self, event):
        Router(Nums.V2F5.value, Nums.TOGGLE.value)

    #VOICE3 and FILTERS
    def editVoice3(self, event):
        if (self.combo_box_3.GetValue() == "Square"):
            Router(Nums.VOICE3.value, Nums.OSC.value)
        elif (self.combo_box_3.GetValue() == "Sine"):
            Router(Nums.VOICE3.value, Nums.SIN.value)
        elif (self.combo_box_3.GetValue() == "Saw"):
            Router(Nums.VOICE3.value, Nums.SAW.value)
        elif (self.combo_box_3.GetValue() == "None"):
            Router(Nums.VOICE3.value, Nums.NONE.value)

    def muteVoice3(self, event):
        Router(Nums.VOICE3.value, Nums.TOGGLE.value)

    def editV3F1(self, event):
        if (self.combo_box_6.GetValue() == "Chorus"):
            Router(Nums.V3F1.value, Nums.CHOR.value)
        elif (self.combo_box_6.GetValue() == "Harmonizer"):
            Router(Nums.V3F1.value, Nums.HARM.value)
        elif (self.combo_box_6.GetValue() == "Frequency Shift"):
            Router(Nums.V3F1.value, Nums.FREQ.value)
        elif (self.combo_box_6.GetValue() == "Reverb"):
            Router(Nums.V3F1.value, Nums.RVRB.value)
        elif (self.combo_box_6.GetValue() == "Distortion"):
            Router(Nums.V3F1.value, Nums.DIST.value)
        elif (self.combo_box_6.GetValue() == "None"):
            Router(Nums.V3F1.value, Nums.NONE.value)

    def muteV3F1(self, event):
        Router(Nums.V3F1.value, Nums.TOGGLE.value)

    def editV3F2(self, event):
        if (self.combo_box_9.GetValue() == "Chorus"):
            Router(Nums.V3F2.value, Nums.CHOR.value)
        elif (self.combo_box_9.GetValue() == "Harmonizer"):
            Router(Nums.V3F2.value, Nums.HARM.value)
        elif (self.combo_box_9.GetValue() == "Frequency Shift"):
            Router(Nums.V3F2.value, Nums.FREQ.value)
        elif (self.combo_box_9.GetValue() == "Reverb"):
            Router(Nums.V3F2.value, Nums.RVRB.value)
        elif (self.combo_box_9.GetValue() == "Distortion"):
            Router(Nums.V3F2.value, Nums.DIST.value)
        elif (self.combo_box_9.GetValue() == "None"):
            Router(Nums.V3F2.value, Nums.NONE.value)

    def muteV3F2(self, event):
        Router(Nums.V3F2.value, Nums.TOGGLE.value)

    def editV3F3(self, event):
        if (self.combo_box_12.GetValue() == "Chorus"):
            Router(Nums.V3F3.value, Nums.CHOR.value)
        elif (self.combo_box_12.GetValue() == "Harmonizer"):
            Router(Nums.V3F3.value, Nums.HARM.value)
        elif (self.combo_box_12.GetValue() == "Frequency Shift"):
            Router(Nums.V3F3.value, Nums.FREQ.value)
        elif (self.combo_box_12.GetValue() == "Reverb"):
            Router(Nums.V3F3.value, Nums.RVRB.value)
        elif (self.combo_box_12.GetValue() == "Distortion"):
            Router(Nums.V3F3.value, Nums.DIST.value)
        elif (self.combo_box_12.GetValue() == "None"):
            Router(Nums.V3F3.value, Nums.NONE.value)

    def muteV3F3(self, event):
        Router(Nums.V3F3.value, Nums.TOGGLE.value)

    def editV3F4(self, event):
        if (self.combo_box_15.GetValue() == "Chorus"):
            Router(Nums.V3F4.value, Nums.CHOR.value)
        elif (self.combo_box_15.GetValue() == "Harmonizer"):
            Router(Nums.V3F4.value, Nums.HARM.value)
        elif (self.combo_box_15.GetValue() == "Frequency Shift"):
            Router(Nums.V3F4.value, Nums.FREQ.value)
        elif (self.combo_box_15.GetValue() == "Reverb"):
            Router(Nums.V3F4.value, Nums.RVRB.value)
        elif (self.combo_box_15.GetValue() == "Distortion"):
            Router(Nums.V3F4.value, Nums.DIST.value)
        elif (self.combo_box_15.GetValue() == "None"):
            Router(Nums.V3F4.value, Nums.NONE.value)

    def muteV3F4(self, event):
        Router(Nums.V3F4.value, Nums.TOGGLE.value)

    def editV3F5(self, event):
        if (self.combo_box_18.GetValue() == "Chorus"):
            Router(Nums.V3F5.value, Nums.CHOR.value)
        elif (self.combo_box_18.GetValue() == "Harmonizer"):
            Router(Nums.V3F5.value, Nums.HARM.value)
        elif (self.combo_box_18.GetValue() == "Frequency Shift"):
            Router(Nums.V3F5.value, Nums.FREQ.value)
        elif (self.combo_box_18.GetValue() == "Reverb"):
            Router(Nums.V3F5.value, Nums.RVRB.value)
        elif (self.combo_box_18.GetValue() == "Distortion"):
            Router(Nums.V3F5.value, Nums.DIST.value)
        elif (self.combo_box_18.GetValue() == "None"):
            Router(Nums.V3F5.value, Nums.NONE.value)

    def muteV3F5(self, event):
        Router(Nums.V3F5.value, Nums.TOGGLE.value)

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
    #Terminate synth audio.
    Router(Nums.STOP.value, Nums.PASS.value)
